version: '3.1'
services :
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - .data/var/lib/postgres/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: code
  admin:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080

  redis:
      image: redis
      restart: always
      ports:
          - 6379:6379