# Generated by Django 3.2.3 on 2023-05-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctors_doctorscategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='video',
        ),
    ]
